#!/bin/sh -e

cat <<EOF
From dilyn:

+ ----------------------------------------------------------------------------------- +
| NOTE: if you get an error about a missing libtinfo.so.6, it's because we don't make |
| one with KISS' ncurses. It is still required for god-knows-why; merely do the       |
|                                                                                     |
| following:                                                                          |
|                                                                                     |
| ln -s /usr/lib/libncursesw.so.6 /usr/lib/libtinfo.so.6                              |
|                                                                                     |
+ ----------------------------------------------------------------------------------- +
EOF
